D12/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('sign/', include('sign.urls')),
    path('protect/', include('protect.urls')),
    path('accounts/', include('allauth.urls')),
]

news/urls.py
from django.urls import path
from .views import PostList, PostDetail, News, PostCreateView, PostUpdateView, PostDeleteView, PostCategoryView, \
    subscribe_to_category, unsubscribe_from_category

app_name = 'news'
urlpatterns = [
    path('', PostList.as_view(), name='news'),
    path('<int:pk>', PostDetail.as_view(), name='new_detail'),
    path('search/', News.as_view(), name='search'),
    path('new/create/', PostCreateView.as_view(), name='new_create'),
    path('new/update/<int:pk>/', PostUpdateView.as_view(), name='new_update'),
    path('new/delete/<int:pk>/', PostDeleteView.as_view(), name='new_delete'),
    path('category/<int:pk>/', PostCategoryView.as_view(), name='category'),
    path('subscribe/<int:pk>/', subscribe_to_category, name='subscribe'),
    path('unsubscribe/<int:pk>/', unsubscribe_from_category, name='unsubscribe'),
]

sign/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView

app_name = 'sign'
urlpatterns = [
   path('login/', LoginView.as_view(), name='login'),
   path('logout/', LogoutView.as_view(), name='logout'),
   path('signup/', RegisterView.as_view(), name='signup'),

]

news/models.py
from audioop import reverse

from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.all().aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.all().aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        allCommentRat = Comment.objects.filter(commentPost__author=self).aggregate(allCommentRating=Sum('rating')).get(
            'rating__sum')
        aRat = 0
        aRat += allCommentRat.get('allCommentRating')

        self.ratingAuthor = pRat * 3 + cRat + aRat
        self.save()

    def __str__(self):
        return self.authorUser.username


class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return f'{self.name}'


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = (
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[:124] + '...'

    def get_category_type(self):
        return self.get_categoryType_display()

    def get_absolute_url(self):
        return reverse('news:new_detail', args=(self.pk,))


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def __str__(self):
        try:
            return self.commentPost.author.authorUser.username
        except:
            return self.commentUser.username

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

news/forms.py
from django.forms import ModelForm

from .models import Post
from django import forms


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['author', 'title', 'category', 'text']
        widgets = {
            'author': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите имя автора',
            }),
            'title': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'category': forms.SelectMultiple(attrs={
                'class': 'form-control',
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-control',
            }),
        }
        labels = {
            'author': 'Автор',
            'title': 'Заголовок',
            'category': 'Категория',
            'text': 'Текст',
        }

news/views.py
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, \
    DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.conf import settings
from .models import Post, Author, Category
from django.utils import timezone
from django.shortcuts import render, redirect
from django.views import View
from django.db.models import QuerySet
from django.core.paginator import Paginator
from .filters import PostFilter
from .forms import PostForm

DEFAULT_FROM_EMAIL = settings.DEFAULT_FROM_EMAIL


class PostList(ListView):
    model = Post
    template_name = 'news/news.html'
    context_object_name = 'news'

    paginate_by = 10

    def get_queryset(self) -> QuerySet(any):
        post_filter = PostFilter(self.request.GET, queryset=Post.objects.all())
        return post_filter.qs.order_by('-dateCreation')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['time_now'] = timezone.localtime(timezone.now())
        context['filter'] = PostFilter(self.request.GET,
                                       queryset=self.get_queryset())
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
        return super().get(request, *args, **kwargs)


class PostDetail(DetailView):
    model = Post
    template_name = 'news/new_detail.html'
    context_object_name = 'news'
    queryset = Post.objects.all()


class News(View):

    def get(self, request):
        news = Post.objects.order_by('-dateCreation')
        p = Paginator(news,
                      1)
        news = p.get_page(
            request.GET.get('page',
                            1))

        data = {
            'news': news,
        }

        return render(request, 'news/search.html', data)


class PostCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'news/new_create.html'
    form_class = PostForm
    context_object_name = 'news'
    permission_required = ('news.add_post', 'news.view_post',)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.user = self.request.user
        post.save()
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'news/new_create.html'
    form_class = PostForm
    context_object_name = 'news'

    def get_object(self, **kwargs):
        id = self.kwargs.get('pk')
        return Post.objects.get(pk=id)


class PostDeleteView(DeleteView):
    template_name = 'news/new_delete.html'
    queryset = Post.objects.all()
    success_url = reverse_lazy('news:news')
    context_object_name = 'news'


class PostCategoryView(ListView):
    model = Post
    template_name = 'news/category.html'
    context_object_name = 'news'
    ordering = ['-dateCreation']
    paginate_by = 10

    def get_queryset(self):
        self.id = self.kwargs.get('pk')
        c = Category.objects.get(id=self.id)
        queryset = Post.objects.filter(category=c)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        category = Category.objects.get(id=self.id)
        subscribed = category.subscribers.filter(email=user.email)
        if not subscribed:
            context['category'] = category
        return context


@login_required
def subscribe_to_category(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    if not category.subscribers.filter(id=user.id).exists():
        category.subscribers.add(user)
        email = user.email
        html = render_to_string(
            'mail/subscribed.html',
            {
                'category': category,
                'user': user,
            },
        )
        msg = EmailMultiAlternatives(
            subject=f'{category} subcription',
            body='',
            from_email=DEFAULT_FROM_EMAIL,
            to=[email, ],
        )
        msg.attach_alternative(html, 'text/html')
        try:
            msg.send()
        except Exception as e:
            print(e)
        return redirect('news:news')
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def unsubscribe_from_category(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    if category.subscribers.filter(id=user.id).exists():
        category.subscribers.remove(user)
    return redirect('protect:index')


def CategoryDetailView(request, pk):
    category = Category.objects.get(pk=pk)
    is_subscribed = True if len(category.subscribers.filter(id=request.user.id)) else False

    return render(request, 'news/category.html',
                  {'category': category,
                   'is_subscribed': is_subscribed,
                   'subscribers': category.subscribers.all()
                   })

news/templates/news/category.html
{% extends 'layout/base.html' %}

{% block title %}
{{ category  }} News
{% endblock title %}

{% block content %}

{% if category.id %}
<div class="subscribed">
  <em>
    Подписаться на категорию <strong> {{ category }}?</strong>
   </em>
  <a href="{% url 'news:subscribe' category.id %}" class="btn btn-outline-primary">
    Подписаться
  </a>
 </div>
{% else %}
<div>
    <em>
        Отписаться от категории  <strong> {{ category }}? </strong>
            </em>
<a href = "{% url 'news:unsubscribe' category.id %}" class="btn btn-outline-primary" >
    Отписаться!</a>
</div>
{% endif %}

<!-- {% include 'news/parts/posts.html' %} -->

{% endblock content %}

news/templates/news/default.html
{% extends 'layout/base.html' %}


{% block title %}
    news
{% endblock title %}

{% block content %}
    <h1>Все новости</h1>
    {{ default }}
{% endblock content %}

news/templates/news/new.html
{% extends 'layout/base.html' %}

{% block title %}
    New
{% endblock title %}

{% block content %}
    <table class="table">
        <tr>
            <th scope="col">
                Заголовок
            </th>
            <th scope="col">
                Дата
            </th>
            <th scope="col">
                Новость
            </th>
        </tr>
        <tr>
            <td>
                {{ new.title|safe }}
            </td>
            <td>
                {{ new.dateCreation }}
            </td>
            <td>
                {{ new.text }}
            </td>
        </tr>
    </table>
{% endblock content %}

news/templates/news/new_create.html
{% extends 'layout/base.html' %}
{% block title %}
    New create
{% endblock title %}

{% block content %}

    <h3>Страница редактирования новости/статьи</h3>

    <form method="POST">
        {% csrf_token %} {{ form }}
        <input class="btn btn-success my-3" type="submit" value="Add"/>
    </form>

{% endblock content %}

news/templates/news/new_delete.html
{% extends 'layout/base.html' %}
{% block title %}
    New delete
{% endblock title %}

{% block content %}

    <h3>Удалить новость/статью?</h3>
    <div class="card">
        <div class="card-header">
            <h4>{{ news.title }}</h4>
            <div>
                Автор: <span class="badge bg-info">{{ news.author }}</span> Тип:
                <span class="badge bg-info">{{ news.get_categoryType_display }}</span>
            </div>
        </div>
        <div class="card-body">{{ news.text }}</div>
    </div>
    <form method="POST">
        {% csrf_token %}
        <input class="btn btn-danger my-3" type="submit" value="Удалить"/>
    </form>

{% endblock content %}

news/templates/news/new_detail.html
{% extends 'layout/base.html' %}
{% block title %}
    New
{% endblock title %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <h3>{{ news.title }}</h3>
            <div>
                Автор: <span class="badge bg-info">{{ news.author }}</span>
                Тип: <span class="badge bg-info">{{ news.get_categoryType_display }}</span>
            </div>
        </div>
        <div class="card-body">{{ news.text }}</div>
    </div>
    <a href="{% url 'news:news' %}" class="btn btn-primary my-3">На главную</a>

{% endblock content %}

news/templates/news/news.html
{% extends 'layout/base.html' %}

{% block title %}
    News
{% endblock title %}

{% block content %}

    <h1>Все новости</h1>
    {% if news %}

        <h3>{{ time_now }}</h3>
        <form method="GET">
            {{ filter.form }}
            <input class="btn btn-primary" type="submit" value="Найти">
        </form>

        <table class="table">
            <tr>
                <th scope="col">
                    Автор
                </th>
                <th scope="col">
                    Заголовок
                </th>
                <th scope="col">
                    Дата
                </th>
                <th scope="col">
                    Новость
                </th>
                <th scope="col">
                    Категория
                </th>


            </tr>
            {% for new in news %}
                <tr>
                    <td>
                        <a href="{% url 'news:new_detail' new.id %}">
                            {{ new.author|safe }}
                        </a>
                    </td>
                    <td>
                        {{ new.title|safe }}
                    </td>
                    <td>
                        {{ new.dateCreation|date:"d-M-Y H:i" }}
                    </td>
                    <td>
                        {{ new.text|truncatechars:50 }}
                    </td>
                    <td>
                        {% for c in new.category.all %}
                            <a href="{% url 'news:category' c.id %}">{{ c }}</a>
                            <br>
                        {% endfor %}
                    <td>
                        <a href="{% url 'news:new_update' new.id %}">
                            Редактировать
                        </a>
                        <a href="{% url 'news:new_delete' new.id %}">
                            Удалить
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <a href="{% url 'news:new_create' %}" class="btn btn-primary my-3">Добавить новость/статью</a>
        {% include 'news/parts/paginator.html' %}
    {% else %}
        <!-- Если новостей нет, то сообщаем об этом пользователю  -->
        <h2>Новостей нет</h2>
    {% endif %}
    <div><a href="{% url 'sign:login' %}" class="btn btn-primary my-3">Войти</a>
        <a href="{% url 'sign:logout' %}" class="btn btn-danger my-3">Выйти</a></div>
{% endblock content %}

news/templates/news/search.html
{% extends 'layout/base.html' %}

{% block title %}
    News
{% endblock title %}

{% block content %}

    <h1>Все новости</h1>

    <form method="GET">
        {{ filter.form }}
        <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы, придётся делать самим -->
        <input class="btn btn-primary" type="submit" value="Найти">
    </form>


{% endblock content %}