D12/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news.urls')),
    path('sign/', include('sign.urls')),
    path('protect/', include('protect.urls')),
    path('accounts/', include('allauth.urls')),
]

news/urls.py
from django.urls import path
from .views import PostList, PostDetail, News, PostCreateView, PostUpdateView, PostDeleteView, PostCategoryView, \
    subscribe_to_category, unsubscribe_from_category

app_name = 'news'
urlpatterns = [
    path('', PostList.as_view(), name='news'),
    path('<int:pk>', PostDetail.as_view(), name='new_detail'),
    path('search/', News.as_view(), name='search'),
    path('new/create/', PostCreateView.as_view(), name='new_create'),
    path('new/update/<int:pk>/', PostUpdateView.as_view(), name='new_update'),
    path('new/delete/<int:pk>/', PostDeleteView.as_view(), name='new_delete'),
    path('category/<int:pk>/', PostCategoryView.as_view(), name='category'),
    path('subscribe/<int:pk>/', subscribe_to_category, name='subscribe'),
    path('unsubscribe/<int:pk>/', unsubscribe_from_category, name='unsubscribe'),
]

protect/urls.py
from django.urls import path
from .views import IndexView, upgrade_me

app_name = 'protect'
urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    path('upgrade/', upgrade_me, name='upgrade'),

]

sign/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView

app_name = 'sign'
urlpatterns = [
   path('login/', LoginView.as_view(), name='login'),
   path('logout/', LogoutView.as_view(), name='logout'),
   path('signup/', RegisterView.as_view(), name='signup'),

]

protect/models.py
from django.db import models

# Create your models here.

protect/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexView(LoginRequiredMixin, TemplateView):
    template_name = 'protect/index.html'
    context_object_name = 'protect'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_author'] = not self.request.user.groups.filter(name='authors').exists()
        return context


@login_required
def upgrade_me(request):
    user = request.user
    author_group = Group.objects.get(name='authors')
    if not request.user.groups.filter(name='authors').exists():
        author_group.user_set.add(user)
    return redirect('/')

protect/templates/protect/index.html
{% extends "main.html" %}

{% block content %}
    <h2>
        Страница авторизованного пользователя {{ request.user.username }}
    </h2>

    <div>
        Здесь может содержаться персональная информация для каждого пользователя
        <div>

            <a class="btn btn-primary" href="{% url 'sign:logout' %}">Выйти</a>

            {% if is_not_author %}

                <a class="btn btn-info" href="{% url 'protect:upgrade' %}">
                    Стать автором
                </a>
            {% else %}
                <h3>
                    Вы являетесь автором
                </h3>
            {% endif %}
            <a href="{% url 'news:news' %}" class="btn btn-primary my-3">На главную</a>
{% endblock content %}